In [2]:
# make sure that the needed packages are installed beforehand! if need be, uncomment and run:
# !pip install numpy pandas scipy mat73

import numpy as np
import pandas as pd
import scipy.io as sio
import mat73

def load_mat_any(path):
    try:
        mat = mat73.loadmat(path)
    except TypeError:
        # fall back to scipy in case
        mat = sio.loadmat(path, simplify_cells=True)
    return mat

In [ ]:
#filepaths. they point to the sample set but be sure to change to desired filepath before running
MAT_PATH = "sample_set/mat/P1_S12_EMG.mat"

mat = load_mat_any(MAT_PATH)
data = mat['miDB']

# confirming shape
print(type(data))
if isinstance(data, list):
    print('n_trials:', len(data))
    print('fields:', list(data[0].keys()))
else:
    print('fields:', list(data.keys()))

<class 'dict'>
fields: ['EMG1k', 'EMG1kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [5]:
def normalize_struct_array(data):
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        # struct-of-arrays -> list-of-dicts
        keys = list(data.keys())
        n = len(data[keys[0]])
        return [{k: data[k][i] for k in keys} for i in range(n)]
    else:
        raise TypeError(f'Unexpected type for data: {type(data)}')

trials = normalize_struct_array(data)
print('n_trials:', len(trials))
print('fields:', list(trials[0].keys()))

n_trials: 35
fields: ['EMG1k', 'EMG1kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [6]:
def to_scalar(x): #for converting numpy outputs to proper scalars
    x = np.asarray(x)
    return x.item() if x.size == 1 else x

In [7]:
# metadata dataframe (one row per trial)
meta_cols = ['TrialID', 'TaskNumber', 'TrialNumber', 'RestTime', 'HoldTime']
trial_meta = pd.DataFrame([
    {k: to_scalar(trial[k]) for k in meta_cols} for trial in trials
])
trial_meta.head()

   TrialID  TaskNumber  TrialNumber  RestTime  HoldTime
0        1           1            1    3000.0    3000.0
1        2           1            2    3000.0    3000.0
2        3           1            3    3000.0    3000.0
3        4           1            4    3000.0    3000.0
4        5           1            5    3000.0    3000.0

In [8]:
# sanity check on array orientation
emg0 = np.asarray(trials[0]['EMG1k'])
print('emg1k shape (trial 0):', emg0.shape)
# expected: (numSamples, numChannels)

emg1k shape (trial 0): (5999, 8)

In [9]:
# Attach EMG1k / EMG1kf to trial_meta as (numSamples x numChannels) arrays, one per trial.
# No long-format table is built anymore -- each row of trial_meta holds the full 2D array
# for that trial in the EMG1k / EMG1kf columns.

TRANSPOSE = False  # set True if emg0.shape above is (numChannels, numSamples)

emg1k_arrays = {}
emg1kf_arrays = {}

for trial in trials:
    tid = to_scalar(trial['TrialID'])
    emg = np.asarray(trial['EMG1k'])
    emgf = np.asarray(trial['EMG1kf'])
    if TRANSPOSE:
        emg = emg.T
        emgf = emgf.T
    emg1k_arrays[tid] = emg    # shape: (numSamples, numChannels)
    emg1kf_arrays[tid] = emgf

trial_meta['EMG1k'] = trial_meta['TrialID'].map(emg1k_arrays)
trial_meta['EMG1kf'] = trial_meta['TrialID'].map(emg1kf_arrays)

trial_meta.head()

,TrialID,TaskNumber,TrialNumber,RestTime,HoldTime,EMG1k,EMG1kf
0,1,1,1,3000.0,3000.0,"[[-13.75, -31.25, 9.5, -28.75, 7.5, -7.5, -3.0...","[[-0.022704024941491676, -0.05160005668520835,..."
1,2,1,2,3000.0,3000.0,"[[-11.0, 9.0, -1.75, 6.5, -8.0, 5.5, -0.25, 1....","[[-0.01816321995319334, 0.014860816325340006, ..."
2,3,1,3,3000.0,3000.0,"[[4.25, -6.0, 3.75, 2.75, 12.0, -11.25, -2.0, ...","[[0.007017607709188338, -0.009907210883560006,..."
3,4,1,4,3000.0,3000.0,"[[18.75, 3.0, 4.25, -1.75, -5.0, 0.0, -11.0, -...","[[0.030960034011125015, 0.004953605441780003, ..."
4,5,1,5,3000.0,3000.0,"[[-9.25, -3.25, -9.0, -5.75, -7.5, -5.25, -5.7...","[[-0.015273616778821674, -0.00536640589526167,..."

In [10]:
# sanity check: confirm stored array shape is (numSamples, numChannels)
trial_meta['EMG1k'].iloc[0].shape

(5999, 8)

In [22]:
# add task metadata from movements.json (the only metadata file -- TaskNumber -> TaskName)

In [ ]:
TASKS_PATH = "M:/Journal Publications/_Submitted/2025_Nwokeabia_MiRPNI/Submission 3/dataset_v4/test/movements.json"
tasks = pd.read_json(TASKS_PATH)
tasks['TaskNumber'] = tasks['TaskNumber'].astype(int)

trial_meta['TaskNumber'] = trial_meta['TaskNumber'].astype(int)

trial_meta = trial_meta.merge(
    tasks[['TaskNumber', 'TaskName']],
    on='TaskNumber',
    how='left'
)

# flag any TaskNumbers not covered by movements.json
missing = trial_meta['TaskName'].isna().sum()
if missing:
    print(f'warning: {missing} trial(s) have a TaskNumber not found in movements.json')

trial_meta.head()

,TrialID,TaskNumber,TrialNumber,RestTime,HoldTime,EMG1k,EMG1kf,TaskName
0,1,1,1,3000.0,3000.0,"[[-13.75, -31.25, 9.5, -28.75, 7.5, -7.5, -3.0...","[[-0.022704024941491676, -0.05160005668520835,...",rest
1,2,1,2,3000.0,3000.0,"[[-11.0, 9.0, -1.75, 6.5, -8.0, 5.5, -0.25, 1....","[[-0.01816321995319334, 0.014860816325340006, ...",rest
2,3,1,3,3000.0,3000.0,"[[4.25, -6.0, 3.75, 2.75, 12.0, -11.25, -2.0, ...","[[0.007017607709188338, -0.009907210883560006,...",rest
3,4,1,4,3000.0,3000.0,"[[18.75, 3.0, 4.25, -1.75, -5.0, 0.0, -11.0, -...","[[0.030960034011125015, 0.004953605441780003, ...",rest
4,5,1,5,3000.0,3000.0,"[[-9.25, -3.25, -9.0, -5.75, -7.5, -5.25, -5.7...","[[-0.015273616778821674, -0.00536640589526167,...",rest