In [22]:
# make sure that the needed packages are installed beforehand! if need be, uncomment and run:
# !pip install numpy pandas scipy mat73

import numpy as np
import pandas as pd
import scipy.io as sio
import mat73

def load_mat_any(path):
    try:
        mat = mat73.loadmat(path)
    except TypeError:
        # fall back to scipy in case
        mat = sio.loadmat(path, simplify_cells=True)
    return mat

In [3]:
ls

LICENSE                      miRPNIvalidation2.m
README.md                    miRPNIvalidationALLTrials.m
csv/                         plot_emg.m
emg_plot.ipynb               plot_emg.mlx
mat_to_dataframe.ipynb

In [23]:
MAT_PATH = "csv/P1_S13.mat"
META_JSON_PATH = "csv/P1_S12.json"

mat = load_mat_any(MAT_PATH)
data = mat['miDB']

# confirming shape
print(type(data))
if isinstance(data, list):
    print('n_trials:', len(data))
    print('fields:', list(data[0].keys()))
else:
    print('fields:', list(data.keys()))

<class 'dict'>
fields: ['EMG1k', 'EMG1kf', 'EMG30k', 'EMG30kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [24]:
def normalize_struct_array(data):
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        # struct-of-arrays -> list-of-dicts
        keys = list(data.keys())
        n = len(data[keys[0]])
        return [{k: data[k][i] for k in keys} for i in range(n)]
    else:
        raise TypeError(f'Unexpected type for data: {type(data)}')

trials = normalize_struct_array(data)
print('n_trials:', len(trials))
print('fields:', list(trials[0].keys()))

n_trials: 100
fields: ['EMG1k', 'EMG1kf', 'EMG30k', 'EMG30kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [25]:
#metadata dataframe
meta_cols = ['TrialID', 'TaskNumber', 'TrialNumber', 'RestTime', 'HoldTime']
trial_meta = pd.DataFrame([{k: trial[k] for k in meta_cols} for trial in trials])
trial_meta.head()

  TrialID TaskNumber TrialNumber RestTime HoldTime
0       1          1           1      255      255
1       2          1           2      255      255
2       3          1           3      255      255
3       4          1           4      255      255
4       5          1           5      255      255

In [26]:
TASKS_PATH = "csv/movements.json"

tasks = pd.read_json(TASKS_PATH)
tasks = tasks.rename(columns={'movementNumber': 'TaskNumber', 'movementName': 'TaskName'})
tasks['TaskNumber'] = tasks['TaskNumber'].astype(int)

# match dtype in trial_meta / emg_df before merging
trial_meta['TaskNumber'] = trial_meta['TaskNumber'].astype(int)

trial_meta = trial_meta.merge(
    tasks[['TaskNumber', 'TaskName']],
    on='TaskNumber',
    how='left'
)
trial_meta.head()

  TrialID  TaskNumber TrialNumber RestTime HoldTime TaskName
0       1           1           1      255      255     rest
1       2           1           2      255      255     rest
2       3           1           3      255      255     rest
3       4           1           4      255      255     rest
4       5           1           5      255      255     rest

In [27]:
# Build the long-format EMG DataFrame

#Check `emg.shape` for the first trial before running on all trials.
#if it's `nChannels x nSamples` instead of `nSamples x nChannels`, transpose with `.T`.

In [29]:
# sanity check on array orientation
emg0 = np.asarray(trials[0]['EMG1k'])
print('emg1k shape (trial 0):', emg0.shape)
# expected: (nSamples, nChannels)

emg1k shape (trial 0): (8000, 8)

In [30]:
TRANSPOSE = False  # set True if the shape above is (nChannels, nSamples)

rows = []
for trial in trials:
    tid = trial['TrialID']
    emg = np.asarray(trial['EMG1k'])
    emgf = np.asarray(trial['EMG1kf'])
    if TRANSPOSE:
        emg = emg.T
        emgf = emgf.T
    n_samples, n_channels = emg.shape

    rows.append(pd.DataFrame({
        'TrialID': tid,
        'sample': np.repeat(np.arange(n_samples), n_channels),
        'channel': np.tile(np.arange(n_channels), n_samples),
        'EMG1k': emg.flatten(),
        'EMG1kf': emgf.flatten(),
    }))

emg_df = pd.concat(rows, ignore_index=True)
emg_df.head()

   TrialID  sample  channel  EMG1k    EMG1kf
0        1       0        0  -0.50 -0.000826
1        1       0        1   7.25  0.011971
2        1       0        2   4.25  0.007018
3        1       0        3  -3.25 -0.005366
4        1       0        4  -3.50 -0.005779

In [ ]:
# add JSON metadata (TaskNumber, onsetIDX)

In [31]:
meta_json = pd.read_json(META_JSON_PATH)

trial_meta['TrialID'] = trial_meta['TrialID'].astype(int)
meta_json['TrialID'] = meta_json['TrialID'].astype(int)
emg_df['TrialID'] = emg_df['TrialID'].astype(int)

trial_meta = trial_meta.merge(
    meta_json[['TrialID', 'TaskNumber']],
    on='TrialID',
    how='left'
)

emg_df = emg_df.merge(trial_meta[['TrialID', 'TaskName']], on='TrialID')

trial_meta.head()

   TrialID  TaskNumber_x TrialNumber RestTime HoldTime TaskName  TaskNumber_y
0        1             1           1      255      255     rest             1
1        2             1           2      255      255     rest             1
2        3             1           3      255      255     rest             1
3        4             1           4      255      255     rest             1
4        5             1           5      255      255     rest             1

In [32]:
emg_df.head()

   TrialID  sample  channel  EMG1k    EMG1kf TaskName
0        1       0        0  -0.50 -0.000826     rest
1        1       0        1   7.25  0.011971     rest
2        1       0        2   4.25  0.007018     rest
3        1       0        3  -3.25 -0.005366     rest
4        1       0        4  -3.50 -0.005779     rest