In [1]:
# make sure that the needed packages are installed beforehand! if need be, uncomment and run:
# !pip install numpy pandas scipy mat73

import numpy as np
import pandas as pd
import scipy.io as sio
import mat73

def load_mat_any(path):
    try:
        mat = mat73.loadmat(path)
    except TypeError:
        # fall back to scipy in case
        mat = sio.loadmat(path, simplify_cells=True)
    return mat

In [2]:
#this filepath points to the sample data, but be sure to update to path of where actual data lives
MAT_PATH = "sample_set/mat/P1_S12_EMG.mat"

mat = load_mat_any(MAT_PATH)
data = mat['miDB']

# confirming shape
print(type(data))
if isinstance(data, list):
    print('n_trials:', len(data))
    print('fields:', list(data[0].keys()))
else:
    print('fields:', list(data.keys()))

<class 'dict'>
fields: ['EMG1k', 'EMG1kf', 'EMG30k', 'EMG30kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [3]:
def normalize_struct_array(data):
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        # struct-of-arrays -> list-of-dicts
        keys = list(data.keys())
        n = len(data[keys[0]])
        return [{k: data[k][i] for k in keys} for i in range(n)]
    else:
        raise TypeError(f'Unexpected type for data: {type(data)}')

trials = normalize_struct_array(data)
print('n_trials:', len(trials))
print('fields:', list(trials[0].keys()))

n_trials: 100
fields: ['EMG1k', 'EMG1kf', 'EMG30k', 'EMG30kf', 'HoldTime', 'MAVs', 'RestTime', 'TaskNumber', 'TrialID', 'TrialNumber']

In [4]:
def to_scalar(x): #for converting numpy outputs to proper scalars
    x = np.asarray(x)
    return x.item() if x.size == 1 else x

In [5]:
# metadata dataframe (one row per trial)
meta_cols = ['TrialID', 'TaskNumber', 'TrialNumber', 'RestTime', 'HoldTime']
trial_meta = pd.DataFrame([
    {k: to_scalar(trial[k]) for k in meta_cols} for trial in trials
])
trial_meta.head()

   TrialID  TaskNumber  TrialNumber  RestTime  HoldTime
0        1           1            1      4000      4000
1        2           1            2      4000      4000
2        3           1            3      4000      4000
3        4           1            4      4000      4000
4        5           1            5      4000      4000

In [6]:
# sanity check on array orientation
emg0 = np.asarray(trials[0]['EMG1k'])
print('emg1k shape (trial 0):', emg0.shape)
# expected: (numSamples, numChannels)

emg1k shape (trial 0): (8000, 8)

In [7]:
# Attach EMG1k / EMG1kf to trial_meta as (numSamples x numChannels) arrays, one per trial.
# No long-format table is built anymore -- each row of trial_meta holds the full 2D array
# for that trial in the EMG1k / EMG1kf columns.

TRANSPOSE = False  # set True if emg0.shape above is (numChannels, numSamples)

emg1k_arrays = {}
emg1kf_arrays = {}

for trial in trials:
    tid = to_scalar(trial['TrialID'])
    emg = np.asarray(trial['EMG1k'])
    emgf = np.asarray(trial['EMG1kf'])
    if TRANSPOSE:
        emg = emg.T
        emgf = emgf.T
    emg1k_arrays[tid] = emg    # shape: (numSamples, numChannels)
    emg1kf_arrays[tid] = emgf

trial_meta['EMG1k'] = trial_meta['TrialID'].map(emg1k_arrays)
trial_meta['EMG1kf'] = trial_meta['TrialID'].map(emg1kf_arrays)

trial_meta.head()

,TrialID,TaskNumber,TrialNumber,RestTime,HoldTime,EMG1k,EMG1kf
0,1,1,1,4000,4000,"[[0.16479691395682805, 4.231175270803911, -0.7...","[[-0.017564747915344778, 1.040593184026, 0.006..."
1,2,1,2,4000,4000,"[[37.838981928421674, 1.8288342789176415, -1.6...","[[6.863550535099749, 0.6227908735581286, -0.13..."
2,3,1,3,4000,4000,"[[106.16820952008253, -0.33569997476228325, 0....","[[19.415730447786483, -0.015840430167471043, -..."
3,4,1,4,4000,4000,"[[-149.8464574490582, -2.2214716664688057, -1....","[[-27.925317711053015, -0.21606106775562298, -..."
4,5,1,5,4000,4000,"[[107.00465999738736, -0.49832675371345025, -1...","[[19.57235768004946, -0.20976000340732934, -0...."

In [8]:
# sanity check: confirm stored array shape is (numSamples, numChannels)
trial_meta['EMG1k'].iloc[0].shape

(8000, 8)

In [9]:
# add task metadata from movements.json (the only metadata file -- TaskNumber -> TaskName)

In [10]:
#this filepath points to the sample data, but be sure to update to path of where actual data lives
TASKS_PATH = "sample_set/movements.json"
tasks = pd.read_json(TASKS_PATH)
tasks['TaskNumber'] = tasks['TaskNumber'].astype(int)

trial_meta['TaskNumber'] = trial_meta['TaskNumber'].astype(int)

trial_meta = trial_meta.merge(
    tasks[['TaskNumber', 'TaskName']],
    on='TaskNumber',
    how='left'
)

# flag any TaskNumbers not covered by movements.json
missing = trial_meta['TaskName'].isna().sum()
if missing:
    print(f'warning: {missing} trial(s) have a TaskNumber not found in movements.json')

trial_meta.head()

,TrialID,TaskNumber,TrialNumber,RestTime,HoldTime,EMG1k,EMG1kf,TaskName
0,1,1,1,4000,4000,"[[0.16479691395682805, 4.231175270803911, -0.7...","[[-0.017564747915344778, 1.040593184026, 0.006...",rest
1,2,1,2,4000,4000,"[[37.838981928421674, 1.8288342789176415, -1.6...","[[6.863550535099749, 0.6227908735581286, -0.13...",rest
2,3,1,3,4000,4000,"[[106.16820952008253, -0.33569997476228325, 0....","[[19.415730447786483, -0.015840430167471043, -...",rest
3,4,1,4,4000,4000,"[[-149.8464574490582, -2.2214716664688057, -1....","[[-27.925317711053015, -0.21606106775562298, -...",rest
4,5,1,5,4000,4000,"[[107.00465999738736, -0.49832675371345025, -1...","[[19.57235768004946, -0.20976000340732934, -0....",rest